### ISSUE TITLE
Allow encrypted connection with self-signed certificates

### ISSUE THREAD

**Issue by Poquaruse** [krambox/buderus2mqtt#5]
Hi there,

Thank you for providing this mqtt-gateway. It works very well for me!
I'd like to connect via mqtts using self-signed certificates. This doesn't seem to be possible right now. hm2mqtt.js for example (https://github.com/hobbyquaker/hm2mqtt.js) uses a flag (-e HM2MQTT_INSECURE="true") which allows that. Would it be possible to add this?

Thanks and best regards!

**Comment by krambox** [comment]
Solved with 5bf29767573869de1def098c0975c8abf770286d

**Comment by Poquaruse** [comment]
Super, vielen Dank!
